<a href="https://colab.research.google.com/github/Saiee2508/AI-/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def bfs(src, target):
    queue = [src]    # Queue to explore nodes
    visited = []     # Visited nodes

    while queue:
        state = queue.pop(0)
        visited.append(state)

        print_puzzle(state)

        if state == target:
            print("\nSuccess! Goal state achieved!")
            return

        # Get possible moves and append to queue if not visited
        for move in possible_moves(state, visited):
            if move not in visited and move not in queue:
                queue.append(move)

In [3]:
def possible_moves(state, visited):
    b = state.index(0)  # Position of empty tile (0)
    directions = []

    if b > 2: directions.append('u')  # Move up
    if b < 6: directions.append('d')  # Move down
    if b % 3 > 0: directions.append('l')  # Move left
    if b % 3 < 2: directions.append('r')  # Move right

    return [gen(state, dir, b) for dir in directions if gen(state, dir, b) not in visited]

In [4]:
def gen(state, direction, b):
    new_state = state.copy()
    swaps = {'u': -3, 'd': 3, 'l': -1, 'r': 1}
    new_b = b + swaps[direction]
    new_state[b], new_state[new_b] = new_state[new_b], new_state[b]
    return new_state

In [5]:
def print_puzzle(state):
    print(np.array(state).reshape(3, 3), "\n")

# Initial setup
src = [1, 2, 3, 4, 5, 6, 0, 7, 8]
target = [1, 2, 3, 4, 5, 6, 7, 8, 0]

print("Initial state:")
print_puzzle(src)

print("Goal state:")
print_puzzle(target)

print("BFS solution:")
bfs(src, target)

Initial state:
[[1 2 3]
 [4 5 6]
 [0 7 8]] 

Goal state:
[[1 2 3]
 [4 5 6]
 [7 8 0]] 

BFS solution:
[[1 2 3]
 [4 5 6]
 [0 7 8]] 

[[1 2 3]
 [0 5 6]
 [4 7 8]] 

[[1 2 3]
 [4 5 6]
 [7 0 8]] 

[[0 2 3]
 [1 5 6]
 [4 7 8]] 

[[1 2 3]
 [5 0 6]
 [4 7 8]] 

[[1 2 3]
 [4 0 6]
 [7 5 8]] 

[[1 2 3]
 [4 5 6]
 [7 8 0]] 


Success! Goal state achieved!
