<a href="https://colab.research.google.com/github/Saiee2508/AI-/blob/main/Assigbment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Constants for players
PLAYER_X = 1  # AI
PLAYER_O = -1  # Human
EMPTY = 0

# Function to initialize the board
def initialize_board():
    return np.zeros((3, 3), dtype=int)

# Function to check for a winner
def check_winner(board):
    for row in board:
        if abs(sum(row)) == 3:
            return np.sign(sum(row))

    for col in board.T:
        if abs(sum(col)) == 3:
            return np.sign(sum(col))

    if abs(sum(board.diagonal())) == 3:
        return np.sign(sum(board.diagonal()))

    if abs(sum(np.fliplr(board).diagonal())) == 3:
        return np.sign(sum(np.fliplr(board).diagonal()))

    return 0  # No winner

# Function to check if the board is full
def is_board_full(board):
    return not np.any(board == EMPTY)


In [2]:
# Minimax function
def minimax(board, depth, is_maximizing):
    winner = check_winner(board)

    if winner == PLAYER_X:
        return 10 - depth  # AI wins
    elif winner == PLAYER_O:
        return depth - 10  # Human wins
    elif is_board_full(board):
        return 0  # Draw

    if is_maximizing:
        best_score = -np.inf
        for row in range(3):
            for col in range(3):
                if board[row, col] == EMPTY:
                    board[row, col] = PLAYER_X  # AI move
                    score = minimax(board, depth + 1, False)
                    board[row, col] = EMPTY  # Undo move
                    best_score = max(best_score, score)
        return best_score
    else:
        best_score = np.inf
        for row in range(3):
            for col in range(3):
                if board[row, col] == EMPTY:
                    board[row, col] = PLAYER_O  # Human move
                    score = minimax(board, depth + 1, True)
                    board[row, col] = EMPTY  # Undo move
                    best_score = min(best_score, score)
        return best_score


In [3]:
def find_best_move(board):
    best_score = -np.inf
    best_move = (-1, -1)

    for row in range(3):
        for col in range(3):
            if board[row, col] == EMPTY:
                board[row, col] = PLAYER_X  # AI move
                score = minimax(board, 0, False)
                board[row, col] = EMPTY  # Undo move
                if score > best_score:
                    best_score = score
                    best_move = (row, col)

    return best_move


In [ ]:
def play_game():
    board = initialize_board()

    while True:
        print(board)

        # Player's turn (Human)
        row, col = map(int, input("Enter your move (row col): ").split())
        if board[row, col] != EMPTY:
            print("Invalid move. Try again.")
            continue
        board[row, col] = PLAYER_O

        if check_winner(board):
            print("You win!")
            break

        if is_board_full(board):
            print("It's a draw!")
            break

        # AI's turn (Minimax)
        ai_move = find_best_move(board)
        board[ai_move] = PLAYER_X

        if check_winner(board):
            print("AI wins!")
            break

        if is_board_full(board):
            print("It's a draw!")
            break

play_game()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Enter your move (row col): 0 0
[[-1  0  0]
 [ 0  1  0]
 [ 0  0  0]]
Enter your move (row col): 1 1 
Invalid move. Try again.
[[-1  0  0]
 [ 0  1  0]
 [ 0  0  0]]
Enter your move (row col): 2 2 
[[-1  1  0]
 [ 0  1  0]
 [ 0  0 -1]]
Enter your move (row col): 2 1
[[-1  1  0]
 [ 0  1  0]
 [ 1 -1 -1]]
